### ISSUE TITLE
index.6c2583f….js:17308 Warning: `NaN` is an invalid value for the `left` css style property. Check the render method of `Image`.

### ISSUE THREAD

**Issue by stefensuhat** [TeamWertarbyte/material-ui-image#11]
component:

```
<Image
         src={menu.photos.web}
          color={placeholderColor}
           loadingSize={30}
           alt={menu.name}
           style={{ minHeight: '143px', height: '100%' }
/>
```

**Comment by saschb2b** [comment]
I don't use a left css value. The progress spinner does. 
`left={style && style.width ? (style.width / 2) - (loadingSize) : styles.root.width / 2 - (loadingSize / 2)}`

Try to fiddle aroudn with your style prop. 100% seems to provide null I guess
Otherwise this comp needs an update to the latest mui code.
ProgressSpinner has changed a lot.

I'll update it asap, let you know and we see if this fixes your issue.

**Comment by saschb2b** [comment]
I can't reproduce your error. Please try version 1.4.0 and post more informatino about your parent div. Seems to be an inheritance issue.
